### ISSUE TITLE
Image 404s

### ISSUE THREAD

**Issue by ajorgensen** [hubot-scripts/hubot-shipit#1]
The following image seems to not exist anymore:

https://img.skitch.com/20111026-r2wsngtu4jftwxmsytdke6arwd.png

found here: https://github.com/hubot-scripts/hubot-shipit/blob/2cc04deeaf769101eefb13fba5dc0988bc550fe1/src/shipit.coffee#L20

**Comment by technicalpickles** [comment]
Nice catch. I'm wondering if there's a good way to, at a project level, to catch when these URLs go away and automatically file an issue.

**Comment by technicalpickles** [comment]
This is fixed in 0.1.2. You should be able to do like `npm install --save hubot-shipit` in your hubot to update.

**Comment by ajorgensen** [comment]
awesome thanks!

**Comment by technicalpickles** [comment]
Forgot to close.
