### ISSUE TITLE
npm WARN EPEERINVALID hubot-shipit@0.2.0 requires a peer of hubot@2.x but none was installed.

### ISSUE THREAD

**Issue by suriyaa** [hubot-scripts/hubot-shipit#12]
@hubot-scripts team - @technicalpickles @bkeepers @ymendel @michaelansel @spaceninja 

---

Hello guys, :smile: 

I got an **npm error** on my _Windows 10_:

``` bash
C:\Users\Suriyaa\Documents\GitHub\animate-a-name [gh-pages +0 ~1 -0]> npm install
npm WARN EPEERINVALID hubot-shipit@0.2.0 requires a peer of hubot@2.x but none was installed.
C:\Users\Suriyaa\Documents\GitHub\animate-a-name [gh-pages +0 ~1 -0]>
```

> I'm using GitHub Desktop, Git Shell, PowerShell and CMD but it still not working!
- My project: https://github.com/SuriyaaKudoIsc/animate-a-name
- My `package.json` file: https://github.com/SuriyaaKudoIsc/animate-a-name/blob/gh-pages/package.json
- My `external-scripts.json` file: https://github.com/SuriyaaKudoIsc/animate-a-name/blob/gh-pages/external-scripts.json

> What should I do?

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by suriyaa** [comment]
ping @gr2m @technicalpickles

**Comment by AndreasHogan** [comment]
solved? I am facing the same

**Comment by suriyaa** [comment]
I had the same issue. I removed the `hubot-shipit` package from `package.json`.

**Comment by AndreasHogan** [comment]
thanx
